Update test-flow.yml to allow ssh to ec2

diff --git a/.github/workflows/test-flow.yml b/.github/workflows/test-flow.yml
--- a/.github/workflows/test-flow.yml
+++ b/.github/workflows/test-flow.yml
@@ -3,7 +3,7 @@ name: AOSP Build on EC2 with Docker JOBS
 on:
   push:
     branches:
-      - test
+      - main
   workflow_dispatch:
 permissions:
   id-token: write
@@ -15,164 +15,155 @@ jobs:
       instance_ip: ${{ env.INSTANCE_IP }}
       instance_id: ${{ env.INSTANCE_ID }}
     steps:
-      - name: Configure AWS Credentials
-        run: |
-          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
-          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          export AWS_REGION=eu-north-1
-  
-      - name: Launch EC2 Instance
-        id: set_instance
-        run: |
-            UBUNTU_AMI_ID=$(aws ec2 describe-images --owners 099720109477 \
-              --filters "Name=name,Values=ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-*" \
-              --query 'Images | sort_by(@, &CreationDate)[-1].ImageId' --output text \
-              --region $AWS_REGION)
-    
-            SUBNET_ID=$(aws ec2 describe-subnets --region $AWS_REGION --query 'Subnets[0].SubnetId' --output text)
-            SG_ID=$(aws ec2 describe-security-groups --region $AWS_REGION --query 'SecurityGroups[0].GroupId' --output text)
-    
-            INSTANCE_ID=$(aws ec2 run-instances --image-id $UBUNTU_AMI_ID \
-              --count 1 --instance-type c5.4xlarge \
-              --key-name praveenkeyAWS \
-              --security-group-ids $SG_ID \
-              --subnet-id $SUBNET_ID \
-              --block-device-mappings '[{"DeviceName": "/dev/sda1", "Ebs": {"VolumeSize": 500, "DeleteOnTermination": true}}]' \
-              --query "Instances[0].InstanceId" --output text \
-              --region $AWS_REGION)
-    
-            echo "INSTANCE_ID=$INSTANCE_ID" >> $GITHUB_ENV
-    
-            INSTANCE_IP=$(aws ec2 describe-instances --instance-ids $INSTANCE_ID --query "Reservations[0].Instances[0].PublicIpAddress" --output text --region $AWS_REGION)
-            echo "INSTANCE_IP=$INSTANCE_IP" >> $GITHUB_ENV
+    - name: Get GitHub Runner Public IP
+      run: |
+        PUBLIC_IP=$(curl -s http://checkip.amazonaws.com)
+        echo "GitHub Runner Public IP: $PUBLIC_IP"
+        echo "PUBLIC_IP=$PUBLIC_IP" >> $GITHUB_ENV
+        
+    - name: Export Build Number
+      run: echo "BUILD_NUMBER=${{ github.run_number }}" >> $GITHUB_ENV
+      
+    - name: Configure AWS Credentials Manually
+      run: |
+        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
+        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+        aws configure set region eu-north-1
+    - name: Validate AWS Authentication
+      run: |
+        aws sts get-caller-identity
+    - name: Update AWS Security Group
+      run: |
+        aws ec2 authorize-security-group-ingress --group-id sg-0b717514e2fcd22ce \
+        --protocol tcp --port 22 --cidr $PUBLIC_IP/32
+    - name: Launch EC2 Instance
+      id: set_instance
+      run: |
+        INSTANCE_NAME="AOSP-Build-Instance-$(date +%Y%m%d%H%M%S)"
+        UBUNTU_AMI_ID=$(aws ec2 describe-images --owners 099720109477 \
+          --filters "Name=name,Values=ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-*" \
+          --query 'Images | sort_by(@, &CreationDate)[-1].ImageId' --output text)
+        SUBNET_ID=$(aws ec2 describe-subnets --query 'Subnets[0].SubnetId' --output text)
+        INSTANCE_ID=$(aws ec2 run-instances --image-id $UBUNTU_AMI_ID \
+          --count 1 --instance-type c5.4xlarge \
+          --key-name praveenkeyAWS \
+          --security-group-ids sg-0b717514e2fcd22ce \
+          --subnet-id $SUBNET_ID \
+          --block-device-mappings '[{"DeviceName": "/dev/sda1", "Ebs": {"VolumeSize": 500, "DeleteOnTermination": true}}]' \
+           --tag-specifications "ResourceType=instance,Tags=[{Key=Name,Value=$INSTANCE_NAME}]" \
+          --query "Instances[0].InstanceId" --output text)
+        echo "INSTANCE_ID=$INSTANCE_ID" >> $GITHUB_ENV
+        INSTANCE_IP=$(aws ec2 describe-instances --instance-ids $INSTANCE_ID --query "Reservations[0].Instances[0].PublicIpAddress" --output text)
+        echo "INSTANCE_IP=$INSTANCE_IP" >> $GITHUB_ENV
+        echo "INSTANCE_NAME=$INSTANCE_NAME" >> $GITHUB_ENV
 
-
-      - name: Wait for EC2 Instance to Start
-        run: aws ec2 wait instance-running --instance-ids $INSTANCE_ID
-
-      - name: Ensure EC2 Instance Is Fully Initialized
-        run: |
-          while true; do
-            INSTANCE_STATE=$(aws ec2 describe-instance-status --instance-ids $INSTANCE_ID --query "InstanceStatuses[0].InstanceState.Name" --output text)
-            SYSTEM_STATUS=$(aws ec2 describe-instance-status --instance-ids $INSTANCE_ID --query "InstanceStatuses[0].SystemStatus.Status" --output text)
-            INSTANCE_STATUS=$(aws ec2 describe-instance-status --instance-ids $INSTANCE_ID --query "InstanceStatuses[0].InstanceStatus.Status" --output text)
-
-            echo "Current State: $INSTANCE_STATE | System Status: $SYSTEM_STATUS | Instance Status: $INSTANCE_STATUS"
-
-            if [[ "$INSTANCE_STATE" == "running" && "$SYSTEM_STATUS" == "ok" && "$INSTANCE_STATUS" == "ok" ]]; then
-              echo "Instance is fully initialized!"
-              break
-            fi
-            sleep 10
-          done
-
-      - name: Setup SSH Key for EC2 Access
-        run: |
-          echo "${{ secrets.AWS_SSH_PRIVATE_KEY }}" > private-key.pem
-          chmod 600 private-key.pem
-      - name: Configure Swap Space
-        run: |
-          ssh -i private-key.pem -o StrictHostKeyChecking=no ubuntu@${INSTANCE_IP} << "EOF"
-            sudo fallocate -l 64G /swapfile
-            sudo chmod 600 /swapfile
-            sudo mkswap /swapfile
-            sudo swapon /swapfile
-            echo '/swapfile swap swap defaults 0 0' | sudo tee -a /etc/fstab
-            sudo sysctl vm.swappiness=10
-            echo 'vm.swappiness=10' | sudo tee -a /etc/sysctl.conf
-          EOF
-      - name: Install Docker on EC2
-        run: |
-          ssh -i private-key.pem -o StrictHostKeyChecking=no ubuntu@${INSTANCE_IP} << "EOF"
-            sudo apt update && sudo apt install -y docker.io
-            sudo usermod -aG docker ubuntu
-            sudo systemctl restart docker
-          EOF
-      - name: Authenticate with GitHub Container Registry
-        run: |
-          ssh -i private-key.pem -o StrictHostKeyChecking=no ubuntu@$(aws ec2 describe-instances --instance-ids $INSTANCE_ID --query "Reservations[0].Instances[0].PublicIpAddress" --output text) << EOF
-            echo "${{ secrets.GHCR_PAT   }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
-          EOF
-      - name: Authenticate with GitHub Container Registry
-        run: |
+    - name: Setup SSH Key for EC2 Access
+      run: |
+        echo "${{ secrets.AWS_SSH_PRIVATE_KEY }}" > private-key.pem
+        chmod 600 private-key.pem
+    - name: Configure Swap Space
+      run: |
+        ssh -i private-key.pem -o StrictHostKeyChecking=no ubuntu@${INSTANCE_IP} << "EOF"
+          sudo fallocate -l 64G /swapfile
+          sudo chmod 600 /swapfile
+          sudo mkswap /swapfile
+          sudo swapon /swapfile
+          echo '/swapfile swap swap defaults 0 0' | sudo tee -a /etc/fstab
+          sudo sysctl vm.swappiness=10
+          echo 'vm.swappiness=10' | sudo tee -a /etc/sysctl.conf
+        EOF
+    - name: Install Docker on EC2
+      run: |
+        ssh -i private-key.pem -o StrictHostKeyChecking=no ubuntu@${INSTANCE_IP} << "EOF"
+          sudo apt update && sudo apt install -y docker.io
+          sudo usermod -aG docker ubuntu
+          sudo systemctl restart docker
+        EOF
+    - name: Authenticate with GitHub Container Registry
+      run: |
+        ssh -i private-key.pem -o StrictHostKeyChecking=no ubuntu@$(aws ec2 describe-instances --instance-ids $INSTANCE_ID --query "Reservations[0].Instances[0].PublicIpAddress" --output text) << EOF
           echo "${{ secrets.GHCR_PAT   }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
+        EOF
+    - name: Authenticate with GitHub Container Registry
+      run: |
+        echo "${{ secrets.GHCR_PAT   }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
 
-      - name: Check and Use Prebuilt Docker Image
-        run: |
-          ssh -i private-key.pem -o StrictHostKeyChecking=no ubuntu@$(aws ec2 describe-instances --instance-ids $INSTANCE_ID --query "Reservations[0].Instances[0].PublicIpAddress" --output text) << 'EOF'
-            set -e  # Stop execution on failure
-            echo "Checking if Docker image exists in GHCR..."
+    - name: Check and Use Prebuilt Docker Image
+      run: |
+        ssh -i private-key.pem -o StrictHostKeyChecking=no ubuntu@$(aws ec2 describe-instances --instance-ids $INSTANCE_ID --query "Reservations[0].Instances[0].PublicIpAddress" --output text) << 'EOF'
+          set -e  # Stop execution on failure
+          echo "Checking if Docker image exists in GHCR..."
+          
+          docker pull ghcr.io/${{ github.repository_owner }}/aosp-build-docker:1.0 || IMAGE_NOT_FOUND="true"
+
+
+         if [[ -z "$IMAGE_NOT_FOUND" ]]; then
+            echo "✅ Docker image found in GHCR, running container..."
+            docker run -d --name aosp-container --restart unless-stopped -v /home/ubuntu/aosp:/workspace ghcr.io/${{ github.repository_owner }}/aosp-build-docker:1.0
+          else
+            echo "⚠️ Docker image not found, building and pushing to GHCR..."
+            mkdir -p /home/ubuntu/aosp && cd /home/ubuntu/aosp
             
-            docker pull ghcr.io/${{ github.repository_owner }}/aosp-build-docker:1.0 || IMAGE_NOT_FOUND="true"
+            echo "FROM ubuntu:20.04" > Dockerfile
+            echo "ENV DEBIAN_FRONTEND=noninteractive" >> Dockerfile
+            echo "RUN apt update && apt install -y git curl python3 python3-pip openjdk-11-jdk wget unzip gcc g++ make libncurses5 libncurses5-dev bison flex gperf zip zlib1g-dev ccache lzop lsb-release sudo python-is-python3" >> Dockerfile
+            
+            # Ensure timezone configuration runs before installing tzdata
+            echo "RUN ln -fs /usr/share/zoneinfo/Asia/Kolkata /etc/localtime" >> Dockerfile
+            echo "RUN echo 'Asia/Kolkata' > /etc/timezone" >> Dockerfile
+            echo "RUN apt update && apt install -y tzdata" >> Dockerfile
+            echo "RUN dpkg-reconfigure --frontend noninteractive tzdata" >> Dockerfile
+            echo "RUN apt update && sudo apt install -y ninja-build rsync awscli" >> Dockerfile
+            
+            # Install repo and setup environment
+            echo "RUN mkdir -p /usr/local/bin && curl -o /usr/local/bin/repo https://storage.googleapis.com/git-repo-downloads/repo" >> Dockerfile
+            echo "RUN chmod a+x /usr/local/bin/repo && ln -s /usr/local/bin/repo /usr/bin/repo" >> Dockerfile
+            
+            echo "WORKDIR /workspace" >> Dockerfile
+            echo "COPY entrypoint.sh /entrypoint.sh" >> Dockerfile
+            echo "RUN chmod +x /entrypoint.sh" >> Dockerfile
+            echo "ENTRYPOINT [\"/entrypoint.sh\"]" >> Dockerfile
+            
+            echo "#!/bin/bash" > entrypoint.sh
+            echo "exec tail -f /dev/null" >> entrypoint.sh
+            chmod +x entrypoint.sh
 
+            
+            echo "Building Docker image..."
+            docker build -t ghcr.io/${{ github.repository_owner }}/aosp-build-docker:1.0 . || {
+                echo "❌ Failed to build Docker image!"
+                exit 1
+            }
+            echo "Pushing Docker image to GHCR..."
+            docker push ghcr.io/${{ github.repository_owner }}/aosp-build-docker:1.0 && echo "✅ Image successfully pushed!"
+            echo "Running newly built container..."
+            docker run -d --name aosp-container --restart unless-stopped -v /home/ubuntu/aosp:/workspace ghcr.io/${{ github.repository_owner }}/aosp-build-docker:1.0
+          fi
+        EOF
 
-           if [[ -z "$IMAGE_NOT_FOUND" ]]; then
-              echo "✅ Docker image found in GHCR, running container..."
-              docker run -d --name aosp-container --restart unless-stopped -v /home/ubuntu/aosp:/workspace ghcr.io/${{ github.repository_owner }}/aosp-build-docker:1.0
-            else
-              echo "⚠️ Docker image not found, building and pushing to GHCR..."
-              mkdir -p /home/ubuntu/aosp && cd /home/ubuntu/aosp
-              
-              echo "FROM ubuntu:20.04" > Dockerfile
-              echo "ENV DEBIAN_FRONTEND=noninteractive" >> Dockerfile
-              echo "RUN apt update && apt install -y git curl python3 python3-pip openjdk-11-jdk wget unzip gcc g++ make libncurses5 libncurses5-dev bison flex gperf zip zlib1g-dev ccache lzop lsb-release sudo python-is-python3" >> Dockerfile
-              
-              # Ensure timezone configuration runs before installing tzdata
-              echo "RUN ln -fs /usr/share/zoneinfo/Asia/Kolkata /etc/localtime" >> Dockerfile
-              echo "RUN echo 'Asia/Kolkata' > /etc/timezone" >> Dockerfile
-              echo "RUN apt update && apt install -y tzdata" >> Dockerfile
-              echo "RUN dpkg-reconfigure --frontend noninteractive tzdata" >> Dockerfile
-              echo "RUN apt update && sudo apt install -y ninja-build rsync awscli" >> Dockerfile
-              
-              # Install repo and setup environment
-              echo "RUN mkdir -p /usr/local/bin && curl -o /usr/local/bin/repo https://storage.googleapis.com/git-repo-downloads/repo" >> Dockerfile
-              echo "RUN chmod a+x /usr/local/bin/repo && ln -s /usr/local/bin/repo /usr/bin/repo" >> Dockerfile
-              
-              echo "WORKDIR /workspace" >> Dockerfile
-              echo "COPY entrypoint.sh /entrypoint.sh" >> Dockerfile
-              echo "RUN chmod +x /entrypoint.sh" >> Dockerfile
-              echo "ENTRYPOINT [\"/entrypoint.sh\"]" >> Dockerfile
-              
-              echo "#!/bin/bash" > entrypoint.sh
-              echo "exec tail -f /dev/null" >> entrypoint.sh
-              chmod +x entrypoint.sh
+    - name: Ensure Log Directory Exists
+      run: |
+        ssh -i private-key.pem -o StrictHostKeyChecking=no ubuntu@${INSTANCE_IP} << EOF
+          sudo mkdir -p /workspace/logs
+          sudo chmod -R 777 /workspace
+          sudo touch /workspace/logs/repo_sync.log
+        EOF
+    - name: Repo Init & Sync
+      run: |
+        ssh -i private-key.pem -o StrictHostKeyChecking=no -o ServerAliveInterval=60 -o TCPKeepAlive=yes -o ConnectTimeout=30 ubuntu@${INSTANCE_IP} << EOF
+          docker exec aosp-container bash -c "
+            rm -rf /workspace/.repo &&
+            mkdir -p /workspace/logs
+            echo 'Initializing repo...'
+            repo init -u https://android.googlesource.com/platform/manifest -b refs/tags/android-platform-14.0.0_r19
+            echo 'Syncing repo...'
+             for i in {1..3}; do
+              repo sync -c -j$(nproc) 2>&1 | tee /workspace/logs/repo_sync.log && break || sleep 10
+            done
+          "
+        EOF
 
-              
-              echo "Building Docker image..."
-              docker build -t ghcr.io/${{ github.repository_owner }}/aosp-build-docker:1.0 . || {
-                  echo "❌ Failed to build Docker image!"
-                  exit 1
-              }
-              echo "Pushing Docker image to GHCR..."
-              docker push ghcr.io/${{ github.repository_owner }}/aosp-build-docker:1.0 && echo "✅ Image successfully pushed!"
-              echo "Running newly built container..."
-              docker run -d --name aosp-container --restart unless-stopped -v /home/ubuntu/aosp:/workspace ghcr.io/${{ github.repository_owner }}/aosp-build-docker:1.0
-            fi
-          EOF
-
-      - name: Ensure Log Directory Exists
-        run: |
-          ssh -i private-key.pem -o StrictHostKeyChecking=no ubuntu@${INSTANCE_IP} << EOF
-            sudo mkdir -p /workspace/logs
-            sudo chmod -R 777 /workspace
-            sudo touch /workspace/logs/repo_sync.log
-          EOF
-      - name: Repo Init & Sync
-        run: |
-          ssh -i private-key.pem -o StrictHostKeyChecking=no -o ServerAliveInterval=60 -o TCPKeepAlive=yes -o ConnectTimeout=30 ubuntu@${INSTANCE_IP} << EOF
-            docker exec aosp-container bash -c "
-              rm -rf /workspace/.repo &&
-              mkdir -p /workspace/logs
-              echo 'Initializing repo...'
-              repo init -u https://android.googlesource.com/platform/manifest -b refs/tags/android-platform-14.0.0_r19
-              echo 'Syncing repo...'
-               for i in {1..3}; do
-                repo sync -c -j$(nproc) 2>&1 | tee /workspace/logs/repo_sync.log && break || sleep 10
-              done
-            "
-          EOF
-
-  build_aosp:
+build_aosp:
     needs: setup_aosp
     runs-on: ubuntu-latest
     timeout-minutes: 720
